kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: namespace-reader
rules:
- apiGroups: [""]  # "" indicates the core API group
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
