apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/managed-by: JMO
    k8s-app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
        restart: "0"
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Release.Name }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/minifi/minifi-current/conf/config.yml
              name: minificonfig
              subPath: config.yml
            - mountPath: /opt/minifi/minifi-current/conf/minifi-log.properties
              name: minificonfig
              subPath: minifi-log.properties
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /var/log/journal
              name: varlogjournal
              readOnly: true
      dnsPolicy: ClusterFirst
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: {{ .Values.serviceAccount | quote }}
      serviceAccountName: {{ .Values.serviceAccountName | quote }}
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-config
          name: minificonfig
        - hostPath:
            path: /var/log
            type: ""
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: varlibdockercontainers
        - hostPath:
            path: /var/log/journal
            type: ""
          name: varlogjournal
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
