# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MiNiFi Config Version: 3
Flow Controller:
  name: MiNiFi Flow
Processors:
- id: 2f2a3b47-f5ba-49f6-82b5-bc1c86b96e27
  name: GetFile
  class: org.apache.nifi.minifi.processors.GetFile
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 1000 ms
  penalization period: 30000 ms
  yield period: 1000 ms
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Input Directory: /tmp/getfile_dir
    Keep Source File: 'true'
    Recurse Subdirectories: 'true'
    Ignore Hidden Files: 'false'
    Minimum File Size: '1 MB'
- id: e143601d-de4f-44ba-a6ec-d1f97d77ec94
  name: PutFile
  class: org.apache.nifi.minifi.processors.PutFile
  max concurrent tasks: 1
  scheduling strategy: EVENT_DRIVEN
  penalization period: 30000 ms
  yield period: 1000 ms
  run duration nanos: 0
  auto-terminated relationships list:
  - failure
  - success
  Properties:
    Conflict Resolution Strategy: fail
    Create Missing Directories: 'true'
    Directory: /tmp/out_dir
Connections:
- id: 098a56ba-f4bf-4323-a3f3-6f8a5e3586bf
  name: GetFile/success/PutFile
  source id: 2f2a3b47-f5ba-49f6-82b5-bc1c86b96e27
  source relationship names:
  - success
  destination id: e143601d-de4f-44ba-a6ec-d1f97d77ec94
  max work queue size: 10000
  max work queue data size: 10 MB
  flowfile expiration: 0 seconds
  queue prioritizer class: ''
Controller Services: []
Remote Process Groups: []
