# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MiNiFi Config Version: 3
Flow Controller:
  name: MiNiFi Flow
Processors:
- name: Tail /tmp/input/test_file.log
  id: 962c76c4-013e-40c0-ac21-9fd6db4593a3
  class: org.apache.nifi.minifi.processors.TailFile
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 1000 ms
  Properties:
    File to Tail: /tmp/input/test_file.log
- name: PushGrafanaLokiREST
  id: 6a9f6c0e-f70c-4778-be8b-ca2494eb0042
  class: org.apache.nifi.minifi.processors.PushGrafanaLokiREST
  scheduling strategy: EVENT_DRIVEN
  auto-terminated relationships list:
  - failure
  - success
  Properties:
    Url: http://127.0.0.1:3100/
    Stream Labels: job=minifi,id=logs
    Log Line Metadata Attributes: filename
    Max Batch Size: '50'
Connections:
- name: TailFile/success/PushGrafanaLokiREST
  id: 32f1aa1b-05c8-4fc1-941f-1e3dc70cb1b2
  source id: 962c76c4-013e-40c0-ac21-9fd6db4593a3
  source relationship names:
  - success
  destination id: 6a9f6c0e-f70c-4778-be8b-ca2494eb0042
Controller Services: []
Remote Process Groups: []
