# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the \"License\"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an \"AS IS\" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MiNiFi Config Version: 3
Flow Controller:
  name: MiNiFi Flow
Processors:
- id: 6ccd8be9-4aa3-4b86-ae10-0a68668f1c25
  name: FetchS3Object
  class: org.apache.nifi.minifi.aws.processors.FetchS3Object
  max concurrent tasks: 1
  scheduling strategy: EVENT_DRIVEN
  penalization period: 30000 ms
  yield period: 1000 ms
  run duration nanos: 0
  auto-terminated relationships list:
  - failure
  Properties:
    AWS Credentials Provider service: AWSCredentialsService
    Bucket: test_bucket
    Communications Timeout: 30 sec
- id: 6f2c20f5-e990-4d9f-bfd6-f7471e3df469
  name: ListS3
  class: org.apache.nifi.minifi.aws.processors.ListS3
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 10000 ms
  penalization period: 30000 ms
  yield period: 1000 ms
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    AWS Credentials Provider service: AWSCredentialsService
    Bucket: test_bucket
    Communications Timeout: 30 sec
- id: 73fd7f54-7639-4f27-b20b-889708f493cb
  name: LogAttribute
  class: org.apache.nifi.minifi.processors.LogAttribute
  max concurrent tasks: 1
  scheduling strategy: EVENT_DRIVEN
  penalization period: 30000 ms
  yield period: 1000 ms
  run duration nanos: 0
  auto-terminated relationships list:
  - success
  Properties:
    Attributes to Ignore:
    Attributes to Log:
    FlowFiles To Log: '1'
    Hexencode Payload: 'false'
    Log Level:
    Log Payload: 'false'
    Log Prefix:
    Maximum Payload Line Length: '80'
Controller Services:
- id: 2094d776-2006-4d02-9bb9-28eac9d0fc95
  name: AWSCredentialsService
  type: org.apache.nifi.minifi.aws.controllers.AWSCredentialsService
  Properties:
    Access Key:
    Credentials File:
    Secret Key:
    Use Default Credentials: 'true'
Connections:
- id: 2c13ddd6-543e-4e37-a295-e4cb8fe85fa5
  name: FetchS3Object/success/LogAttribute
  source id: 6ccd8be9-4aa3-4b86-ae10-0a68668f1c25
  source relationship names:
  - success
  destination id: 73fd7f54-7639-4f27-b20b-889708f493cb
  max work queue size: 10000
  max work queue data size: 10 MB
  flowfile expiration: 0 seconds
  queue prioritizer class: ''
- id: 7895c12e-9657-4baa-a8ec-6b8cb11f32cd
  name: ListS3/success/FetchS3Object
  source id: 6f2c20f5-e990-4d9f-bfd6-f7471e3df469
  source relationship names:
  - success
  destination id: 6ccd8be9-4aa3-4b86-ae10-0a68668f1c25
  max work queue size: 10000
  max work queue data size: 10 MB
  flowfile expiration: 0 seconds
  queue prioritizer class: ''
Remote Process Groups: []
