# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MiNiFi Config Version: 3
Flow Controller:
  name: MiNiFi Flow
Processors:
- name: Fetch S3 object from test_bucket
  id: 6ccd8be9-4aa3-4b86-ae10-0a68668f1c25
  class: org.apache.nifi.minifi.aws.processors.FetchS3Object
  scheduling strategy: EVENT_DRIVEN
  auto-terminated relationships list:
  - failure
  Properties:
    AWS Credentials Provider service: AWSCredentialsService
    Bucket: test_bucket
    Communications Timeout: 30 sec
- name: List test_bucket S3 bucket
  id: 6f2c20f5-e990-4d9f-bfd6-f7471e3df469
  class: org.apache.nifi.minifi.aws.processors.ListS3
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 10000 ms
  Properties:
    AWS Credentials Provider service: AWSCredentialsService
    Bucket: test_bucket
    Communications Timeout: 30 sec
- name: Log S3 object attributes
  id: 73fd7f54-7639-4f27-b20b-889708f493cb
  class: org.apache.nifi.minifi.processors.LogAttribute
  scheduling strategy: EVENT_DRIVEN
  auto-terminated relationships list:
  - success
  Properties:
    FlowFiles To Log: '0'
Controller Services:
- name: AWSCredentialsService
  id: 2094d776-2006-4d02-9bb9-28eac9d0fc95
  class: org.apache.nifi.minifi.aws.controllers.AWSCredentialsService
  Properties:
    Use Default Credentials: 'true'
Connections:
- name: FetchS3Object/success/LogAttribute
  id: 2c13ddd6-543e-4e37-a295-e4cb8fe85fa5
  source id: 6ccd8be9-4aa3-4b86-ae10-0a68668f1c25
  source relationship names:
  - success
  destination id: 73fd7f54-7639-4f27-b20b-889708f493cb
- name: ListS3/success/FetchS3Object
  id: 7895c12e-9657-4baa-a8ec-6b8cb11f32cd
  source id: 6f2c20f5-e990-4d9f-bfd6-f7471e3df469
  source relationship names:
  - success
  destination id: 6ccd8be9-4aa3-4b86-ae10-0a68668f1c25
Remote Process Groups: []
