# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MiNiFi Config Version: 3
Flow Controller:
  name: MiNiFi Flow
Processors:
- Properties:
    Input Directory: /tmp/input
  auto-terminated relationships list: []
  class: org.apache.nifi.processors.standard.GetFile
  id: 45c2a56e-7c29-42f3-8c1d-89c0c84a6ee7
  name: GetFile
  penalization period: 30 sec
  run duration nanos: 0
  scheduling period: 2 sec
  scheduling strategy: TIMER_DRIVEN
  yield period: 1 sec
Remote Processing Groups:
- Input Ports:
  - Properties: {}
    id: 4222cd3a-746e-3497-abd0-b7695faa750c
    max concurrent tasks: 1
    name: to_nifi
  id: 38878f84-23cd-4aaa-9c45-45151bb2d681
  name: RemoteProcessGroup
  timeout: 30 sec
  url: http://nifi:8080/nifi
  yield period: 3 sec
Connections:
- destination id: 4222cd3a-746e-3497-abd0-b7695faa750c
  drop empty: 'false'
  name: 001d6605-c353-4a20-8534-8663f31d1c8d
  source id: 45c2a56e-7c29-42f3-8c1d-89c0c84a6ee7
  source relationship name: success
Controller Services: []
