FROM opensearchproject/opensearch:latest
ADD opensearch.yml /usr/share/opensearch/config/opensearch.yml
ADD certs/admin.pem /usr/share/opensearch/config/admin.pem
ADD certs/admin-key.pem /usr/share/opensearch/config/admin-key.pem
ADD certs/root-ca.pem /usr/share/opensearch/config/root-ca.pem
