FROM opensearchproject/opensearch:2.6.0
COPY opensearch.yml /usr/share/opensearch/config/opensearch.yml
COPY certs/admin.pem /usr/share/opensearch/config/admin.pem
COPY certs/admin-key.pem /usr/share/opensearch/config/admin-key.pem
COPY certs/root-ca.pem /usr/share/opensearch/config/root-ca.pem
