name: minifi-cpp
version: '0.5.0'
summary: Apache NiFi MiNiFi Cpp
description: Collecting on the edge

grade: devel
confinement: devmode

parts:
    minifi-cpp:
        source: https://github.com/apache/nifi-minifi-cpp.git
        source-type: git
        source-tag: rel/minifi-cpp-0.5.0
        plugin: cmake
        configflags:
            - -DCMAKE_INSTALL_PREFIX=/opt/minifi
            - -DENABLE_GPS=TRUE
            - -DENABLE_LIBRDKAFKA=TRUE
            - -DENABLE_MQTT=TRUE
            - -DENABLE_BUSTACHE=TRUE
            - -DPORTABLE=ON
            - -DBUILD_ROCKSDB=ON
            - -DCMAKE_CXX_FLAGS='-W'
        build-packages:
            - make
            - cmake
            - build-essential
        stage-packages:
            - build-essential
            - liblzma5
            - libc6
            - libusb-1.0-0
            - libcurl4-openssl-dev
            - libgps-dev
            - libheimbase1-heimdal
            - libheimntlm0-heimdal
            - libhx509-5-heimdal
            - libidn2-0
            - libkrb5-3
            - libldap-2.4-2
            - libnghttp2-14
            - libpython3.5-dev
            - libroken18-heimdal
            - librtmp1
            - libsasl2-2
            - libssl1.0.0
            - libwind0-heimdal
            - zlib1g

apps:
    minifi-cpp:
        command: opt/minifi/bin/minifi
